name: onion_base_app
description: A new Flutter project.
# 以下の行は、`flutter pub publish`を使って誤ってpub.devにパッケージを公開してしまうのを防ぎます。
# プライベート・パッケージの場合は、この方法が望ましいです。
# pub.devに公開したい場合は、この行を削除する。
publish_to: "none"

# 以下は、アプリケーションのバージョンとビルド番号の定義です。
# バージョン番号とは、1.2.43のようにドットで区切られた3つの数字で記載し、
# その後ろに「+」とオプションのビルド番号が続きます。
# (例)1.2.43+1
# flutterではバージョンとビルド番号の両方を上書きすることができます。
# --build-name と --build-number をそれぞれ指定することで上書きできます。
# Androidでは、build-name は versionName として使用され、build-number は versionCode として使用されます。
# Androidのバージョニングについては、下記を参照して下さい。
# https://developer.android.com/studio/publish/versioning
# iOSでは、build-name は CFBundleShortVersionString として使用され、build-number は CFBundleVersion として使用されます。
# iOSのバージョニングについては、下記を参照して下さい。
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windowsでは、build-name が製品バージョンとファイルバージョンの
# メジャー、マイナー、パッチの各部分として使わます。ビルド番号はビルドの接尾辞として使われます。
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# dependenciesは、あなたのパッケージが動作するために必要な他のパッケージを指定します。.
# パッケージの依存関係を自動的に最新版にアップグレードするには
# `flutter pub upgrade --major-versions` を実行してみて下さい。
# あるいは、以下のバージョン番号を以下のように変更することで、
# 依存関係をpub.devで利用可能な最新バージョンに手動で更新することもできます。
# 新しいバージョンが利用可能な依存関係を確認するには,
# `flutter pub outdated` も実行してみて下さい。
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # 以下は、アプリケーションに Cupertino Icons フォントを追加するためのものです。
  # iOSスタイルのアイコンはCupertinoIconsクラスと一緒に使ってください。
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  meta: ^1.16.0
  mockito: ^5.4.5
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 以下の "flutter_lints "パッケージには、
  # 良いコーディングプラクティスを奨励するための、推奨lintsのセットが含まれています。
  # パッケージが提供するlintセットは、パッケージのルートにある`analysis_options.yaml`ファイルで有効になります。
  # 特定のlintsルールの無効化と追加ルールの有効化については、このファイルを参照してください。
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  architecture_linter: ^0.3.0
  linteo: ^1.3.0

# このファイルの一般的なDart部分に関する情報については、
# 次のページを参照して下さい: https://dart.dev/tools/pub/pubspec

# 以下のセクションはFlutterパッケージに特化したものです。
flutter:
  generate: true

  # 以下の行は、Material Iconsクラスのアイコンを使用できるように、
  # Material Iconsフォントがアプリケーションに含まれていることを保証しています。
  uses-material-design: true

  # アプリケーションにアセットを追加するには、下記ようにアセットセクションを追加します。
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # 画像アセットは、1つ以上の解像度固有の"variants"を参照できます。
  # https://flutter.dev/assets-and-images/#resolution-aware を参照してください。

  # パッケージの依存関係からのアセット追加に関する詳細については、下記を参照して下さい。
  # https://flutter.dev/assets-and-images/#from-packages

  # アプリケーションにカスタムフォントを追加するには、
  # この "flutter "セクションにフォントセクションを追加します。
  # このリスト内の各エントリには、フォントファミリー名を示す "family "キーと、
  # フォントのアセットやその他の記述子を示すistを示す "fonts "キーが必要です。
  # (例)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # パッケージ依存のフォントに関する詳細については、下記を参照して下さい。
  # https://flutter.dev/custom-fonts/#from-packages
